/* CVS $Id: $ */
package com.hp.hpl.jena.vocabulary;
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/carlos/Desktop/lom.owl 
 * @author Auto-generated by schemagen on 24 Apr 2013 19:23 
 */
public class LOM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.owl-ontologies.com/lom.owl#";
    //public static final String NS = "http://ltsc.ieee.org/xsd/LOM#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "version 1.0";
    
    public static final Property hasPatternPart = m_model.createProperty( "http://www.owl-ontologies.com/lom.owl#hasPatternPart" );
    
    public static final Property isPartOfValuePartition = m_model.createProperty( "http://www.owl-ontologies.com/lom.owl#isPartOfValuePartition" );
    
    /** <p>This category provides comments on the educational use of this learning object, 
     *  and information on when and by whom the comments were created. This category 
     *  enables educators to share their assessments of learning objects, suggestions 
     *  for use, etc.</p>
     */
    public static final Resource Annotation = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Annotation" );
    
    /** <p>This category describes where this learning object falls within a particular 
     *  classification system. To define multiple classifications, there may be multiple 
     *  instances of this category.</p>
     */
    public static final Resource Classification = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Classification" );
    
    /** <p>Those entities (i.e., people, organizations) that have contributed to the 
     *  state of this learning object during its life cycle (e.g., creation, edits, 
     *  publication).</p>
     */
    public static final Resource Contribute = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Contribute" );
    
    /** <p>This category describes the key educational or pedagogic characteristics of 
     *  this learning object. This is the pedagogical information essential to those 
     *  involved in achieving a quality learning experience. The audience for this 
     *  metadata includes teachers, managers, authors and learners.</p>
     */
    public static final Resource Educational = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Educational" );
    
    public static final Resource Element = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Element" );
    
    public static final Resource ElementComponent = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#ElementComponent" );
    
    /** <p>This category groups the general information that describes this learning 
     *  object as a whole.</p>
     */
    public static final Resource General = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#General" );
    
    public static final Resource Identifier = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Identifier" );
    
    public static final Resource LOM = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#LOM" );
    
    /** <p>This category describes the history and current state of this learning object 
     *  and those who have affected this learning object during its evolution.</p>
     */
    public static final Resource LifeCycle = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#LifeCycle" );
    
    /** <p>This category describes this metadata record itself (rather than the learning 
     *  object that this record describes).</p>
     */
    public static final Resource MetaMetaData = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#MetaMetaData" );
    
    /** <p>Grouping of multiple requirements. The composite requirement is satisfied 
     *  when one of the component requirements is satisfied, i.e., the logical connector 
     *  is OR.</p>
     */
    public static final Resource OrComposite = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#OrComposite" );
    
    /** <p>The technical capabilities necessary for using this learning object. If there 
     *  are multiple requirements, then all are required, i.e., the logical connector 
     *  is AND.</p>
     */
    public static final Resource Requirement = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Requirement" );
    
    public static final Resource Rights = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Rights" );
    
    /** <p>A particular term within a taxonomy. A taxon is a node that has a defined 
     *  label or term. A taxon may also have an alphanumeric designation or identifier 
     *  for standardized reference. Either or both the label and the entry may be 
     *  used to designate a particular taxon. An ordered list of taxons creates a 
     *  taxonomic path, i.e., "taxonomic stairway": this is a path from a more general 
     *  to more specific entry in a classification.</p>
     */
    public static final Resource Taxon = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Taxon" );
    
    /** <p>A taxonomic path in a specific classification system. Each succeeding level 
     *  is a refinement in the definition of the preceding level. There may be different 
     *  paths, in the same or different classifications, which describe the same characteristic.</p>
     */
    public static final Resource TaxonPath = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#TaxonPath" );
    
    /** <p>This category describes the technical requirements and characteristics of 
     *  this learning object.</p>
     */
    public static final Resource Technical = m_model.createResource( "http://www.owl-ontologies.com/lom.owl#Technical" );
    
}
